# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Dr Charles Patrick Martin: Preprint Archive"
email: cpm@charlesmartin.au
description: "Open-access preprints, papers, and research outputs in music technology and musical AI."
baseurl: "" # set to /preprints at build time by the deploy workflow
url: "https://charlesmartin.au"
twitter_username: cpmpercussion
github_username:  cpmpercussion

scholar:
  style: apa
  source: _bibliography
  bibliography: publications.bib
  repository: preprints
  bibliography_template: bibliography
  group_by: year
  group_order: descending
  bibliography_list_tag: "ul"
  bibliography_item_tag: "li"


# Build settings
markdown: kramdown
theme: monophase
plugins:
  - jekyll-feed
  - jekyll-scholar

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
